version: '3'

services:
  tailscale-ha:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailscale-ha
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - ./docker-data:/data
      - ./docker-share:/share
    ports:
      - "41641:41641/udp" 