version: '3'

services:
  tailscale-ha:
    image: tailscale-ha:mac-x86
    platform: linux/amd64
    container_name: tailscale-ha
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - ./docker-data:/data
      - ./docker-share:/share
    ports:
      - "8099:8099"
      - "41641:41641/udp"
